export const CareerBannerTab = () => import('../..\\components\\career\\career-banner-tab.vue' /* webpackChunkName: "components/career-banner-tab" */).then(c => wrapFunctional(c.default || c))
export const CareerCompanyOverview = () => import('../..\\components\\career\\career-company-overview.vue' /* webpackChunkName: "components/career-company-overview" */).then(c => wrapFunctional(c.default || c))
export const CareerConsultant = () => import('../..\\components\\career\\career-consultant.vue' /* webpackChunkName: "components/career-consultant" */).then(c => wrapFunctional(c.default || c))
export const CareerJoinEvent = () => import('../..\\components\\career\\career-join-event.vue' /* webpackChunkName: "components/career-join-event" */).then(c => wrapFunctional(c.default || c))
export const CareerOurTeam = () => import('../..\\components\\career\\career-our-team.vue' /* webpackChunkName: "components/career-our-team" */).then(c => wrapFunctional(c.default || c))
export const CareerProfessionalFunctional = () => import('../..\\components\\career\\career-professional-functional.vue' /* webpackChunkName: "components/career-professional-functional" */).then(c => wrapFunctional(c.default || c))
export const CareerQuestion = () => import('../..\\components\\career\\career-question.vue' /* webpackChunkName: "components/career-question" */).then(c => wrapFunctional(c.default || c))
export const BusinessPlanGoogleAdQuestionForm = () => import('../..\\components\\business-plan-google-ad\\business-plan-google-ad-question-form.vue' /* webpackChunkName: "components/business-plan-google-ad-question-form" */).then(c => wrapFunctional(c.default || c))
export const BaseAboutPage = () => import('../..\\components\\base\\base-about-page.vue' /* webpackChunkName: "components/base-about-page" */).then(c => wrapFunctional(c.default || c))
export const BaseContactUs = () => import('../..\\components\\base\\base-contact-us.vue' /* webpackChunkName: "components/base-contact-us" */).then(c => wrapFunctional(c.default || c))
export const BaseDivisions = () => import('../..\\components\\base\\base-divisions.vue' /* webpackChunkName: "components/base-divisions" */).then(c => wrapFunctional(c.default || c))
export const BaseFoundersBio = () => import('../..\\components\\base\\base-founders-bio.vue' /* webpackChunkName: "components/base-founders-bio" */).then(c => wrapFunctional(c.default || c))
export const BaseGoogleAd = () => import('../..\\components\\base\\base-google-ad.vue' /* webpackChunkName: "components/base-google-ad" */).then(c => wrapFunctional(c.default || c))
export const BaseOurTeam = () => import('../..\\components\\base\\base-our-team.vue' /* webpackChunkName: "components/base-our-team" */).then(c => wrapFunctional(c.default || c))
export const BaseServicePages = () => import('../..\\components\\base\\base-service-pages.vue' /* webpackChunkName: "components/base-service-pages" */).then(c => wrapFunctional(c.default || c))
export const BaseSingleInsights = () => import('../..\\components\\base\\base-single-insights.vue' /* webpackChunkName: "components/base-single-insights" */).then(c => wrapFunctional(c.default || c))
export const CommonAsSeenOn = () => import('../..\\components\\common\\common-as-seen-on.vue' /* webpackChunkName: "components/common-as-seen-on" */).then(c => wrapFunctional(c.default || c))
export const CommonBannerTab = () => import('../..\\components\\common\\common-banner-tab.vue' /* webpackChunkName: "components/common-banner-tab" */).then(c => wrapFunctional(c.default || c))
export const CommonBaseTemplate = () => import('../..\\components\\common\\common-base-template.vue' /* webpackChunkName: "components/common-base-template" */).then(c => wrapFunctional(c.default || c))
export const CommonBrandLogo = () => import('../..\\components\\common\\common-brand-logo.vue' /* webpackChunkName: "components/common-brand-logo" */).then(c => wrapFunctional(c.default || c))
export const CommonBusinessChallenge = () => import('../..\\components\\common\\common-business-challenge.vue' /* webpackChunkName: "components/common-business-challenge" */).then(c => wrapFunctional(c.default || c))
export const CommonCategorySlider = () => import('../..\\components\\common\\common-category-slider.vue' /* webpackChunkName: "components/common-category-slider" */).then(c => wrapFunctional(c.default || c))
export const CommonClientWords = () => import('../..\\components\\common\\common-client-words.vue' /* webpackChunkName: "components/common-client-words" */).then(c => wrapFunctional(c.default || c))
export const CommonComments = () => import('../..\\components\\common\\common-comments.vue' /* webpackChunkName: "components/common-comments" */).then(c => wrapFunctional(c.default || c))
export const CommonCompanyOverview = () => import('../..\\components\\common\\common-company-overview.vue' /* webpackChunkName: "components/common-company-overview" */).then(c => wrapFunctional(c.default || c))
export const CommonConsultation = () => import('../..\\components\\common\\common-consultation.vue' /* webpackChunkName: "components/common-consultation" */).then(c => wrapFunctional(c.default || c))
export const CommonContactUs = () => import('../..\\components\\common\\common-contact-us.vue' /* webpackChunkName: "components/common-contact-us" */).then(c => wrapFunctional(c.default || c))
export const CommonCustomStrapiDisplay = () => import('../..\\components\\common\\common-custom-strapi-display.vue' /* webpackChunkName: "components/common-custom-strapi-display" */).then(c => wrapFunctional(c.default || c))
export const CommonDistinctQualities = () => import('../..\\components\\common\\common-distinct-qualities.vue' /* webpackChunkName: "components/common-distinct-qualities" */).then(c => wrapFunctional(c.default || c))
export const CommonDynamicQuestionnaire = () => import('../..\\components\\common\\common-dynamic-questionnaire.vue' /* webpackChunkName: "components/common-dynamic-questionnaire" */).then(c => wrapFunctional(c.default || c))
export const CommonFaq = () => import('../..\\components\\common\\common-faq.vue' /* webpackChunkName: "components/common-faq" */).then(c => wrapFunctional(c.default || c))
export const CommonFeaturedServices = () => import('../..\\components\\common\\common-featured-services.vue' /* webpackChunkName: "components/common-featured-services" */).then(c => wrapFunctional(c.default || c))
export const CommonInterestedService = () => import('../..\\components\\common\\common-interested-service.vue' /* webpackChunkName: "components/common-interested-service" */).then(c => wrapFunctional(c.default || c))
export const CommonModal = () => import('../..\\components\\common\\common-modal.vue' /* webpackChunkName: "components/common-modal" */).then(c => wrapFunctional(c.default || c))
export const CommonOurTeam = () => import('../..\\components\\common\\common-our-team.vue' /* webpackChunkName: "components/common-our-team" */).then(c => wrapFunctional(c.default || c))
export const CommonOurWork = () => import('../..\\components\\common\\common-our-work.vue' /* webpackChunkName: "components/common-our-work" */).then(c => wrapFunctional(c.default || c))
export const CommonQuestionnaireContent = () => import('../..\\components\\common\\common-questionnaire-content.vue' /* webpackChunkName: "components/common-questionnaire-content" */).then(c => wrapFunctional(c.default || c))
export const CommonQuestionsForm = () => import('../..\\components\\common\\common-questions-form.vue' /* webpackChunkName: "components/common-questions-form" */).then(c => wrapFunctional(c.default || c))
export const CommonReadytotalk = () => import('../..\\components\\common\\common-readytotalk.vue' /* webpackChunkName: "components/common-readytotalk" */).then(c => wrapFunctional(c.default || c))
export const CommonShare = () => import('../..\\components\\common\\common-share.vue' /* webpackChunkName: "components/common-share" */).then(c => wrapFunctional(c.default || c))
export const CommonTellMoreAboutProjects = () => import('../..\\components\\common\\common-tell-more-about-projects.vue' /* webpackChunkName: "components/common-tell-more-about-projects" */).then(c => wrapFunctional(c.default || c))
export const CommonToggleContent = () => import('../..\\components\\common\\common-toggle-content.vue' /* webpackChunkName: "components/common-toggle-content" */).then(c => wrapFunctional(c.default || c))
export const CommonVenturePlans = () => import('../..\\components\\common\\common-venture-plans.vue' /* webpackChunkName: "components/common-venture-plans" */).then(c => wrapFunctional(c.default || c))
export const CommonWorkAtTheBestPlace = () => import('../..\\components\\common\\common-work-at-the-best-place.vue' /* webpackChunkName: "components/common-work-at-the-best-place" */).then(c => wrapFunctional(c.default || c))
export const ConsultingOurPortfolio = () => import('../..\\components\\consulting\\consulting-our-portfolio.vue' /* webpackChunkName: "components/consulting-our-portfolio" */).then(c => wrapFunctional(c.default || c))
export const ContactFeaturedServices = () => import('../..\\components\\contact-us\\contact-featured-services.vue' /* webpackChunkName: "components/contact-featured-services" */).then(c => wrapFunctional(c.default || c))
export const ContactPrivatePlacement = () => import('../..\\components\\contact-us\\contact-private-placement.vue' /* webpackChunkName: "components/contact-private-placement" */).then(c => wrapFunctional(c.default || c))
export const ContactUsHeroform = () => import('../..\\components\\contact-us\\contact-us-heroform.vue' /* webpackChunkName: "components/contact-us-heroform" */).then(c => wrapFunctional(c.default || c))
export const ContactUsServiceHelp = () => import('../..\\components\\contact-us\\contact-us-service-help.vue' /* webpackChunkName: "components/contact-us-service-help" */).then(c => wrapFunctional(c.default || c))
export const GoogleAdCustomSoftwareDevelopment = () => import('../..\\components\\google-ad\\google-ad-custom-software-development.vue' /* webpackChunkName: "components/google-ad-custom-software-development" */).then(c => wrapFunctional(c.default || c))
export const GoogleAdHeroform = () => import('../..\\components\\google-ad\\google-ad-heroform.vue' /* webpackChunkName: "components/google-ad-heroform" */).then(c => wrapFunctional(c.default || c))
export const GoogleAdLosHeroform = () => import('../..\\components\\google-ad\\google-ad-los-heroform.vue' /* webpackChunkName: "components/google-ad-los-heroform" */).then(c => wrapFunctional(c.default || c))
export const GoogleAdProjectInfoSubmit = () => import('../..\\components\\google-ad\\google-ad-project-info-submit.vue' /* webpackChunkName: "components/google-ad-project-info-submit" */).then(c => wrapFunctional(c.default || c))
export const HeaderMenuBar = () => import('../..\\components\\header\\header-menu-bar.vue' /* webpackChunkName: "components/header-menu-bar" */).then(c => wrapFunctional(c.default || c))
export const HeaderRightSideBar = () => import('../..\\components\\header\\header-right-side-bar.vue' /* webpackChunkName: "components/header-right-side-bar" */).then(c => wrapFunctional(c.default || c))
export const HeaderTopBar = () => import('../..\\components\\header\\header-top-bar.vue' /* webpackChunkName: "components/header-top-bar" */).then(c => wrapFunctional(c.default || c))
export const HomeAboutClient = () => import('../..\\components\\home\\home-about-client.vue' /* webpackChunkName: "components/home-about-client" */).then(c => wrapFunctional(c.default || c))
export const HomeCareer = () => import('../..\\components\\home\\home-career.vue' /* webpackChunkName: "components/home-career" */).then(c => wrapFunctional(c.default || c))
export const HomeHeroSlider = () => import('../..\\components\\home\\home-hero-slider.vue' /* webpackChunkName: "components/home-hero-slider" */).then(c => wrapFunctional(c.default || c))
export const HomeOurLatestInsights = () => import('../..\\components\\home\\home-our-latest-insights.vue' /* webpackChunkName: "components/home-our-latest-insights" */).then(c => wrapFunctional(c.default || c))
export const HomePrivatePlacement = () => import('../..\\components\\home\\home-private-placement.vue' /* webpackChunkName: "components/home-private-placement" */).then(c => wrapFunctional(c.default || c))
export const HomeSectorChart = () => import('../..\\components\\home\\home-sector-chart.vue' /* webpackChunkName: "components/home-sector-chart" */).then(c => wrapFunctional(c.default || c))
export const HomeSectorExcelled = () => import('../..\\components\\home\\home-sector-excelled.vue' /* webpackChunkName: "components/home-sector-excelled" */).then(c => wrapFunctional(c.default || c))
export const HomeSubscribe = () => import('../..\\components\\home\\home-subscribe.vue' /* webpackChunkName: "components/home-subscribe" */).then(c => wrapFunctional(c.default || c))
export const IconsAproach = () => import('../..\\components\\icons\\icons-aproach.vue' /* webpackChunkName: "components/icons-aproach" */).then(c => wrapFunctional(c.default || c))
export const IconsArrowRightThin = () => import('../..\\components\\icons\\icons-arrow-right-thin.vue' /* webpackChunkName: "components/icons-arrow-right-thin" */).then(c => wrapFunctional(c.default || c))
export const IconsArrowUpThin = () => import('../..\\components\\icons\\icons-arrow-up-thin.vue' /* webpackChunkName: "components/icons-arrow-up-thin" */).then(c => wrapFunctional(c.default || c))
export const IconsArrowUp = () => import('../..\\components\\icons\\icons-arrow-up.vue' /* webpackChunkName: "components/icons-arrow-up" */).then(c => wrapFunctional(c.default || c))
export const IconsAttach = () => import('../..\\components\\icons\\icons-attach.vue' /* webpackChunkName: "components/icons-attach" */).then(c => wrapFunctional(c.default || c))
export const IconsBachelorCandidate = () => import('../..\\components\\icons\\icons-bachelor-candidate.vue' /* webpackChunkName: "components/icons-bachelor-candidate" */).then(c => wrapFunctional(c.default || c))
export const IconsBitcoin = () => import('../..\\components\\icons\\icons-bitcoin.vue' /* webpackChunkName: "components/icons-bitcoin" */).then(c => wrapFunctional(c.default || c))
export const IconsBrokerage = () => import('../..\\components\\icons\\icons-brokerage.vue' /* webpackChunkName: "components/icons-brokerage" */).then(c => wrapFunctional(c.default || c))
export const IconsBuilding = () => import('../..\\components\\icons\\icons-building.vue' /* webpackChunkName: "components/icons-building" */).then(c => wrapFunctional(c.default || c))
export const IconsCalendar = () => import('../..\\components\\icons\\icons-calendar.vue' /* webpackChunkName: "components/icons-calendar" */).then(c => wrapFunctional(c.default || c))
export const IconsCannabis = () => import('../..\\components\\icons\\icons-cannabis.vue' /* webpackChunkName: "components/icons-cannabis" */).then(c => wrapFunctional(c.default || c))
export const IconsCentricity = () => import('../..\\components\\icons\\icons-centricity.vue' /* webpackChunkName: "components/icons-centricity" */).then(c => wrapFunctional(c.default || c))
export const IconsCheckCircle = () => import('../..\\components\\icons\\icons-check-circle.vue' /* webpackChunkName: "components/icons-check-circle" */).then(c => wrapFunctional(c.default || c))
export const IconsCleanTech = () => import('../..\\components\\icons\\icons-clean-tech.vue' /* webpackChunkName: "components/icons-clean-tech" */).then(c => wrapFunctional(c.default || c))
export const IconsCloseMenu = () => import('../..\\components\\icons\\icons-close-menu.vue' /* webpackChunkName: "components/icons-close-menu" */).then(c => wrapFunctional(c.default || c))
export const IconsCloseSearch = () => import('../..\\components\\icons\\icons-close-search.vue' /* webpackChunkName: "components/icons-close-search" */).then(c => wrapFunctional(c.default || c))
export const IconsCloseTime = () => import('../..\\components\\icons\\icons-close-time.vue' /* webpackChunkName: "components/icons-close-time" */).then(c => wrapFunctional(c.default || c))
export const IconsClose = () => import('../..\\components\\icons\\icons-close.vue' /* webpackChunkName: "components/icons-close" */).then(c => wrapFunctional(c.default || c))
export const IconsConsumer = () => import('../..\\components\\icons\\icons-consumer.vue' /* webpackChunkName: "components/icons-consumer" */).then(c => wrapFunctional(c.default || c))
export const IconsDomain = () => import('../..\\components\\icons\\icons-domain.vue' /* webpackChunkName: "components/icons-domain" */).then(c => wrapFunctional(c.default || c))
export const IconsDownBorder = () => import('../..\\components\\icons\\icons-down-border.vue' /* webpackChunkName: "components/icons-down-border" */).then(c => wrapFunctional(c.default || c))
export const IconsDownarrow = () => import('../..\\components\\icons\\icons-downarrow.vue' /* webpackChunkName: "components/icons-downarrow" */).then(c => wrapFunctional(c.default || c))
export const IconsEduction = () => import('../..\\components\\icons\\icons-eduction.vue' /* webpackChunkName: "components/icons-eduction" */).then(c => wrapFunctional(c.default || c))
export const IconsFacebook = () => import('../..\\components\\icons\\icons-facebook.vue' /* webpackChunkName: "components/icons-facebook" */).then(c => wrapFunctional(c.default || c))
export const IconsFinacial = () => import('../..\\components\\icons\\icons-finacial.vue' /* webpackChunkName: "components/icons-finacial" */).then(c => wrapFunctional(c.default || c))
export const IconsGoogleIcon = () => import('../..\\components\\icons\\icons-google-icon.vue' /* webpackChunkName: "components/icons-google-icon" */).then(c => wrapFunctional(c.default || c))
export const IconsHamburger = () => import('../..\\components\\icons\\icons-hamburger.vue' /* webpackChunkName: "components/icons-hamburger" */).then(c => wrapFunctional(c.default || c))
export const IconsHeartCare = () => import('../..\\components\\icons\\icons-heart-care.vue' /* webpackChunkName: "components/icons-heart-care" */).then(c => wrapFunctional(c.default || c))
export const IconsIcon1 = () => import('../..\\components\\icons\\icons-icon1.vue' /* webpackChunkName: "components/icons-icon1" */).then(c => wrapFunctional(c.default || c))
export const IconsIcon2 = () => import('../..\\components\\icons\\icons-icon2.vue' /* webpackChunkName: "components/icons-icon2" */).then(c => wrapFunctional(c.default || c))
export const IconsIcon3 = () => import('../..\\components\\icons\\icons-icon3.vue' /* webpackChunkName: "components/icons-icon3" */).then(c => wrapFunctional(c.default || c))
export const IconsIcon4 = () => import('../..\\components\\icons\\icons-icon4.vue' /* webpackChunkName: "components/icons-icon4" */).then(c => wrapFunctional(c.default || c))
export const IconsIcon5 = () => import('../..\\components\\icons\\icons-icon5.vue' /* webpackChunkName: "components/icons-icon5" */).then(c => wrapFunctional(c.default || c))
export const IconsIcon6 = () => import('../..\\components\\icons\\icons-icon6.vue' /* webpackChunkName: "components/icons-icon6" */).then(c => wrapFunctional(c.default || c))
export const IconsIcon7 = () => import('../..\\components\\icons\\icons-icon7.vue' /* webpackChunkName: "components/icons-icon7" */).then(c => wrapFunctional(c.default || c))
export const IconsInstagramColor = () => import('../..\\components\\icons\\icons-instagram-color.vue' /* webpackChunkName: "components/icons-instagram-color" */).then(c => wrapFunctional(c.default || c))
export const IconsInstagram = () => import('../..\\components\\icons\\icons-instagram.vue' /* webpackChunkName: "components/icons-instagram" */).then(c => wrapFunctional(c.default || c))
export const IconsLinkedin = () => import('../..\\components\\icons\\icons-linkedin.vue' /* webpackChunkName: "components/icons-linkedin" */).then(c => wrapFunctional(c.default || c))
export const IconsLocation = () => import('../..\\components\\icons\\icons-location.vue' /* webpackChunkName: "components/icons-location" */).then(c => wrapFunctional(c.default || c))
export const IconsLogo = () => import('../..\\components\\icons\\icons-logo.vue' /* webpackChunkName: "components/icons-logo" */).then(c => wrapFunctional(c.default || c))
export const IconsManufacturing = () => import('../..\\components\\icons\\icons-manufacturing.vue' /* webpackChunkName: "components/icons-manufacturing" */).then(c => wrapFunctional(c.default || c))
export const IconsMarket = () => import('../..\\components\\icons\\icons-market.vue' /* webpackChunkName: "components/icons-market" */).then(c => wrapFunctional(c.default || c))
export const IconsMbaCandidate = () => import('../..\\components\\icons\\icons-mba-candidate.vue' /* webpackChunkName: "components/icons-mba-candidate" */).then(c => wrapFunctional(c.default || c))
export const IconsMdCandidate = () => import('../..\\components\\icons\\icons-md-candidate.vue' /* webpackChunkName: "components/icons-md-candidate" */).then(c => wrapFunctional(c.default || c))
export const IconsMinus = () => import('../..\\components\\icons\\icons-minus.vue' /* webpackChunkName: "components/icons-minus" */).then(c => wrapFunctional(c.default || c))
export const IconsPhone = () => import('../..\\components\\icons\\icons-phone.vue' /* webpackChunkName: "components/icons-phone" */).then(c => wrapFunctional(c.default || c))
export const IconsPlay = () => import('../..\\components\\icons\\icons-play.vue' /* webpackChunkName: "components/icons-play" */).then(c => wrapFunctional(c.default || c))
export const IconsPlus = () => import('../..\\components\\icons\\icons-plus.vue' /* webpackChunkName: "components/icons-plus" */).then(c => wrapFunctional(c.default || c))
export const IconsProfessional = () => import('../..\\components\\icons\\icons-professional.vue' /* webpackChunkName: "components/icons-professional" */).then(c => wrapFunctional(c.default || c))
export const IconsResidential = () => import('../..\\components\\icons\\icons-residential.vue' /* webpackChunkName: "components/icons-residential" */).then(c => wrapFunctional(c.default || c))
export const IconsRightMenuArrow = () => import('../..\\components\\icons\\icons-right-menu-arrow.vue' /* webpackChunkName: "components/icons-right-menu-arrow" */).then(c => wrapFunctional(c.default || c))
export const IconsSave = () => import('../..\\components\\icons\\icons-save.vue' /* webpackChunkName: "components/icons-save" */).then(c => wrapFunctional(c.default || c))
export const IconsSearch = () => import('../..\\components\\icons\\icons-search.vue' /* webpackChunkName: "components/icons-search" */).then(c => wrapFunctional(c.default || c))
export const IconsSelectionArrow = () => import('../..\\components\\icons\\icons-selection-arrow.vue' /* webpackChunkName: "components/icons-selection-arrow" */).then(c => wrapFunctional(c.default || c))
export const IconsShareIcon = () => import('../..\\components\\icons\\icons-share-icon.vue' /* webpackChunkName: "components/icons-share-icon" */).then(c => wrapFunctional(c.default || c))
export const IconsStar = () => import('../..\\components\\icons\\icons-star.vue' /* webpackChunkName: "components/icons-star" */).then(c => wrapFunctional(c.default || c))
export const IconsTeam = () => import('../..\\components\\icons\\icons-team.vue' /* webpackChunkName: "components/icons-team" */).then(c => wrapFunctional(c.default || c))
export const IconsTiktok = () => import('../..\\components\\icons\\icons-tiktok.vue' /* webpackChunkName: "components/icons-tiktok" */).then(c => wrapFunctional(c.default || c))
export const IconsTopmenuarrow = () => import('../..\\components\\icons\\icons-topmenuarrow.vue' /* webpackChunkName: "components/icons-topmenuarrow" */).then(c => wrapFunctional(c.default || c))
export const IconsTwitter = () => import('../..\\components\\icons\\icons-twitter.vue' /* webpackChunkName: "components/icons-twitter" */).then(c => wrapFunctional(c.default || c))
export const IconsUpload = () => import('../..\\components\\icons\\icons-upload.vue' /* webpackChunkName: "components/icons-upload" */).then(c => wrapFunctional(c.default || c))
export const IconsWhiteLogo = () => import('../..\\components\\icons\\icons-white-logo.vue' /* webpackChunkName: "components/icons-white-logo" */).then(c => wrapFunctional(c.default || c))
export const IconsWifi = () => import('../..\\components\\icons\\icons-wifi.vue' /* webpackChunkName: "components/icons-wifi" */).then(c => wrapFunctional(c.default || c))
export const IconsYelpIcon = () => import('../..\\components\\icons\\icons-yelp-icon.vue' /* webpackChunkName: "components/icons-yelp-icon" */).then(c => wrapFunctional(c.default || c))
export const IconsYoutube = () => import('../..\\components\\icons\\icons-youtube.vue' /* webpackChunkName: "components/icons-youtube" */).then(c => wrapFunctional(c.default || c))
export const InputFilterCheckbox = () => import('../..\\components\\input\\input-filter-checkbox.vue' /* webpackChunkName: "components/input-filter-checkbox" */).then(c => wrapFunctional(c.default || c))
export const OurSustainabilityCardWithImage = () => import('../..\\components\\our-sustainability\\our-sustainability-card-with-image.vue' /* webpackChunkName: "components/our-sustainability-card-with-image" */).then(c => wrapFunctional(c.default || c))
export const OurSustainabilityMaterialTopics = () => import('../..\\components\\our-sustainability\\our-sustainability-material-topics.vue' /* webpackChunkName: "components/our-sustainability-material-topics" */).then(c => wrapFunctional(c.default || c))
export const LayoutFooter = () => import('../..\\components\\layout\\layout-footer.vue' /* webpackChunkName: "components/layout-footer" */).then(c => wrapFunctional(c.default || c))
export const LayoutHeader = () => import('../..\\components\\layout\\layout-header.vue' /* webpackChunkName: "components/layout-header" */).then(c => wrapFunctional(c.default || c))
export const SoftwareDevelopmentServices = () => import('../..\\components\\software-google-ad\\software-development-services.vue' /* webpackChunkName: "components/software-development-services" */).then(c => wrapFunctional(c.default || c))
export const SoftwareGoogleAdWhyVenturePlans = () => import('../..\\components\\software-google-ad\\why-venture-plans.vue' /* webpackChunkName: "components/software-google-ad-why-venture-plans" */).then(c => wrapFunctional(c.default || c))
export const TechnologyQuestionsForm = () => import('../..\\components\\technology\\technology-questions-form.vue' /* webpackChunkName: "components/technology-questions-form" */).then(c => wrapFunctional(c.default || c))
export const AboutOurLeadershipVideoSection = () => import('../..\\components\\about\\our-leadership\\about-our-leadership-video-section.vue' /* webpackChunkName: "components/about-our-leadership-video-section" */).then(c => wrapFunctional(c.default || c))
export const CommonBusinessPlanAbout = () => import('../..\\components\\common\\business-plan\\common-business-plan-about.vue' /* webpackChunkName: "components/common-business-plan-about" */).then(c => wrapFunctional(c.default || c))
export const HeaderRightSideBarMenuLanguageEnglish = () => import('../..\\components\\header\\header-right-side-bar-menu\\header-right-side-bar-menu-language-english.vue' /* webpackChunkName: "components/header-right-side-bar-menu-language-english" */).then(c => wrapFunctional(c.default || c))
export const HeaderRightSideBarMenuOffices = () => import('../..\\components\\header\\header-right-side-bar-menu\\header-right-side-bar-menu-offices.vue' /* webpackChunkName: "components/header-right-side-bar-menu-offices" */).then(c => wrapFunctional(c.default || c))

// nuxt/nuxt.js#8607
function wrapFunctional(options) {
  if (!options || !options.functional) {
    return options
  }

  const propKeys = Array.isArray(options.props) ? options.props : Object.keys(options.props || {})

  return {
    render(h) {
      const attrs = {}
      const props = {}

      for (const key in this.$attrs) {
        if (propKeys.includes(key)) {
          props[key] = this.$attrs[key]
        } else {
          attrs[key] = this.$attrs[key]
        }
      }

      return h(options, {
        on: this.$listeners,
        attrs,
        props,
        scopedSlots: this.$scopedSlots,
      }, this.$slots.default)
    }
  }
}
